[versions]
agp = "8.13.2"
kotlin = "2.3.0"
bom = "1.0.13"
material = "1.13.0"
navigation = "2.9.5"
rxandroid = "3.0.2"
rxjava = "3.1.12"

[libraries]
rxandroid = { module = "io.reactivex.rxjava3:rxandroid", version.ref = "rxandroid" }
rxjava = { module = "io.reactivex.rxjava3:rxjava", version.ref = "rxjava" }
sdk-bom = { module = "com.mcards.sdk:bom", version.ref = "bom" }
auth = { module = "com.mcards.sdk:auth" }
cards = { module = "com.mcards.sdk:cards" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

